service: notes-api-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: krisperssonRegularUser
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::619468094687:role/LambdaAPIGatewayDynamoDB

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getNotes:
    handler: functions/getNotes/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: GET
  postNote:
    handler: functions/postNote/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: POST
  editNote:
    handler: functions/editNote/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: PUT
  deleteNote:
    handler: functions/deleteNote/index.handler
    events:
    - httpApi:
        path: '/api/notes'
        method: DELETE
  userLogin:
    handler: functions/userLogin/index.handler
    events:
    - httpApi:
        path: '/api/user/login'
        method: POST
  userSignup:
    handler: functions/userSignup/index.handler
    events:
    - httpApi:
        path: '/api/user/signup'
        method: POST

resources:
  Resources: 
      notesDb:
          Type: AWS::DynamoDB::Table
          Properties: 
              TableName: notes-db
              AttributeDefinitions:
                  - AttributeName: userId
                    AttributeType: S
                  - AttributeName: itemId
                    AttributeType: S
              KeySchema:
                  - AttributeName: userId
                    KeyType: HASH
                  - AttributeName: itemId
                    KeyType: RANGE
              BillingMode: PAY_PER_REQUEST
